### ISSUE TITLE
Feature Request:  Time increments of 100ms

### ISSUE THREAD

**Issue by Ruedii** [OskarDamkjaer/FirefoxDelayWebpage#10]
Studies have shown that 500ms is enough to eliminate the "Crack effect" of current web sites.  I the settings being done in increments of 500ms instead of full seconds should improve this balance.

Some users may find the latency increase to need to be higher or lower for them, depending on the rate of their cognitive process, so obviously you should be able to tune it in increments.

**Comment by OskarDamkjaer** [comment]
I've implemented your feature request! If you'd like to test it out you can do a manual. Otherwise the update should reach you in 24 hours or so :)
