### ISSUE TITLE
Feature Request: Pass through delays

### ISSUE THREAD

**Issue by jcuenod** [OskarDamkjaer/FirefoxDelayWebpage#11]
Well, when you hit the front page of HN, this is what you get, I suppose. Congrats :)

What I'd like (in addition to kicking my HN habit) is to add delay to the links I click from HN so that I can't just wait 7 seconds and then hit a pile of links in the page and read to my heart's content...

**Comment by OskarDamkjaer** [comment]
I think I've got this done! If you'd like you can do a manual update to test it or wait for the next automatic update

**Comment by jcuenod** [comment]
I'll wait for the automatic update at this point. I appreciate the rapid response!
