### ISSUE TITLE
Seems broken on Facebook right now.

### ISSUE THREAD

**Issue by Ruedii** [OskarDamkjaer/FirefoxDelayWebpage#13]
On Facebook.  It seems that this extension is breaking the share to group, share to friend and share buttons (which pull up dialog boxes).  

It wasn't doing so until a few days ago too.  I think Facebook changed how they handle these in a way that breaks with the extension.

**Comment by ghost** [comment]
Right now Facebook post-login won't load anything besides a blank once the timer is finished. It seems that the extension interrupts the scripts from loading.

**Comment by Ruedii** [comment]
That was my guess as well.

**Comment by OskarDamkjaer** [comment]
Oh, thanks for bringing this to my attention! sorry for taking so long to notice this issue. I'll get to it! :)

**Comment by OskarDamkjaer** [comment]
I've found and fixed the bug! I'll release a fix later today! :) Thanks for your patience <3
