### ISSUE TITLE
Dont delay on youtube.com player settings

### ISSUE THREAD

**Issue by VietTralala** [OskarDamkjaer/FirefoxDelayWebpage#17]
The add-on used to not delay actions such as changing resolution/ playback speed/ changing volume in browser player/jumping on timeline. However this changed. Can I set it to optional? I only want the add-on to delay when changing to a different video.

**Comment by OskarDamkjaer** [comment]
Oh no, that's a bug I thought I fixed! Thank you very much for reporting it, I'll get to it right away!

**Comment by OskarDamkjaer** [comment]
@vthuongt Turns out I had a spelling error. Thanks again for reporting, I've deployed a new version and tested it with youtube. You should get the new version automatically today or tomorrow :) 

If you have any new issues feel free to reach out directly to me at delaywebpage@gmail.com

**Comment by VietTralala** [comment]
Thank __you__ for the quick fix and the awesome add-on! Keep up the good work :)
