### ISSUE TITLE
From predefined pages, setting for which are enabled

### ISSUE THREAD

**Issue by osdiab** [OskarDamkjaer/FirefoxDelayWebpage#5]
Until #1 happens a stopgap I'd like is to be able to disable it for some set of the pages, like keep it on for hacker news but turn it off for Youtube since I'm not addicted to that and actually use it for useful things

I'm thinking checkboxes for the list of websites, the ones checked get delayed

**Comment by OskarDamkjaer** [comment]
#1 Should mostly be resolved, so your usecase should be possible now :)
